spring.application.name=StarFall-Forum
server.port=8312

spring.mvc.pathmatch.matching-strategy=path_pattern_parser
spring.config.import=optional:nacos:${spring.application.name}.properties,optional:nacos:${spring.application.name}.prop.properties,optional:nacos:${spring.application.name}.mail.properties,optional:nacos:${spring.application.name}.datasource.properties

nacos.server-addr=127.0.0.1:8412
spring.cloud.nacos.discovery.server-addr=${nacos.server-addr}
spring.cloud.nacos.config.server-addr=${nacos.server-addr}
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100

logging.logback.rollingpolicy.file-name-pattern=logs/starfall-forum-%d{yyyy-MM-dd}.log.gz
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.max-file-size=10MB


