spring.application.name=StarFall-Forum
server.port=8312

spring.mvc.pathmatch.matching-strategy=path_pattern_parser
spring.config.import=optional:nacos:${spring.application.name}.properties,optional:nacos:${spring.application.name}.prop.properties,optional:nacos:${spring.application.name}.mail.properties,optional:nacos:${spring.application.name}.datasource.properties

nacos.server-addr=127.0.0.1:8412
spring.cloud.nacos.discovery.server-addr=${nacos.server-addr}
spring.cloud.nacos.config.server-addr=${nacos.server-addr}
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100

logging.logback.rollingpolicy.file-name-pattern=logs/starfall-forum-%d{yyyy-MM-dd}.log.gz
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.max-file-size=10MB

rsa.key.private=\
    MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAuCzVG3oOQhC/lTRW\u000A\
    0Ejp1aVQpvE7or7svpQDWgfQmzHRQvmEUaqZXtj30BgS9RgFqfNI2ay8Umbvb3J1\u000A\
    qN0FZwIDAQABAkEAib/2cEOdEGqocDciS0yNoF6x8PryiKnWNkBMNXUs4DVgp3QD\u000A\
    NrgDlmdl9p8eyj+Yt3PS9R/ZiOoq2qxwwJYiUQIhANmId1Cn0+xFCSnfaE0muyIs\u000A\
    LFLzVDcZHsuELcqhcwOZAiEA2L5H9yj9G7cHs2tYkpyKrRDG7qqpepogocf6ILd1\u000A\
    8P8CIAsCii9t3x8FO3qAETJedHg9Th0ArdGAFvvr+7lWxJB5AiBnY600i0rhk5eK\u000A\
    0KP5m87S63PZmXMq1qbGRXxdauZJxQIhALPbS46THK2myS6eizsGzQ6Iy/RzJsAr\u000A\
    bT/e/ldQRXPh
rsa.key.public=\
    MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALgs1Rt6DkIQv5U0VtBI6dWlUKbxO6K+\u000A\
    7L6UA1oH0Jsx0UL5hFGqmV7Y99AYEvUYBanzSNmsvFJm729ydajdBWcCAwEAAQ==


